--------------------------------------------------------
--  File created - суббота-мая-13-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table Cart
--------------------------------------------------------

  CREATE TABLE "PIA"."Cart" 
   (	"cart_id" NUMBER, 
	"customer_id" NUMBER, 
	"product_id" NUMBER, 
	"quantity" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT DELETE ON "PIA"."Cart" TO "USERROLE";
  GRANT INSERT ON "PIA"."Cart" TO "USERROLE";
  GRANT UPDATE ON "PIA"."Cart" TO "USERROLE";
  GRANT ALTER ON "PIA"."Cart" TO "USERKA" WITH GRANT OPTION;
  GRANT DELETE ON "PIA"."Cart" TO "USERKA" WITH GRANT OPTION;
  GRANT INDEX ON "PIA"."Cart" TO "USERKA" WITH GRANT OPTION;
  GRANT INSERT ON "PIA"."Cart" TO "USERKA" WITH GRANT OPTION;
  GRANT SELECT ON "PIA"."Cart" TO "USERKA" WITH GRANT OPTION;
  GRANT UPDATE ON "PIA"."Cart" TO "USERKA" WITH GRANT OPTION;
  GRANT REFERENCES ON "PIA"."Cart" TO "USERKA" WITH GRANT OPTION;
  GRANT ON COMMIT REFRESH ON "PIA"."Cart" TO "USERKA" WITH GRANT OPTION;
  GRANT QUERY REWRITE ON "PIA"."Cart" TO "USERKA" WITH GRANT OPTION;
  GRANT DEBUG ON "PIA"."Cart" TO "USERKA" WITH GRANT OPTION;
  GRANT FLASHBACK ON "PIA"."Cart" TO "USERKA" WITH GRANT OPTION;
  GRANT ALTER ON "PIA"."Cart" TO "SYSTEM" WITH GRANT OPTION;
  GRANT DELETE ON "PIA"."Cart" TO "SYSTEM" WITH GRANT OPTION;
  GRANT INDEX ON "PIA"."Cart" TO "SYSTEM" WITH GRANT OPTION;
  GRANT INSERT ON "PIA"."Cart" TO "SYSTEM" WITH GRANT OPTION;
  GRANT SELECT ON "PIA"."Cart" TO "SYSTEM" WITH GRANT OPTION;
  GRANT UPDATE ON "PIA"."Cart" TO "SYSTEM" WITH GRANT OPTION;
  GRANT REFERENCES ON "PIA"."Cart" TO "SYSTEM" WITH GRANT OPTION;
  GRANT READ ON "PIA"."Cart" TO "SYSTEM" WITH GRANT OPTION;
  GRANT ON COMMIT REFRESH ON "PIA"."Cart" TO "SYSTEM" WITH GRANT OPTION;
  GRANT QUERY REWRITE ON "PIA"."Cart" TO "SYSTEM" WITH GRANT OPTION;
  GRANT DEBUG ON "PIA"."Cart" TO "SYSTEM" WITH GRANT OPTION;
  GRANT FLASHBACK ON "PIA"."Cart" TO "SYSTEM" WITH GRANT OPTION;
--------------------------------------------------------
--  DDL for Table Categories
--------------------------------------------------------

  CREATE TABLE "PIA"."Categories" 
   (	"category_id" NUMBER, 
	"category_name" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT ALTER ON "PIA"."Categories" TO "SYSTEM";
  GRANT DELETE ON "PIA"."Categories" TO "SYSTEM";
  GRANT INDEX ON "PIA"."Categories" TO "SYSTEM";
  GRANT INSERT ON "PIA"."Categories" TO "SYSTEM";
  GRANT SELECT ON "PIA"."Categories" TO "SYSTEM";
  GRANT UPDATE ON "PIA"."Categories" TO "SYSTEM";
  GRANT REFERENCES ON "PIA"."Categories" TO "SYSTEM";
  GRANT READ ON "PIA"."Categories" TO "SYSTEM";
  GRANT ON COMMIT REFRESH ON "PIA"."Categories" TO "SYSTEM";
  GRANT QUERY REWRITE ON "PIA"."Categories" TO "SYSTEM";
  GRANT DEBUG ON "PIA"."Categories" TO "SYSTEM";
  GRANT FLASHBACK ON "PIA"."Categories" TO "SYSTEM";
  GRANT ALTER ON "PIA"."Categories" TO "SYS";
  GRANT DELETE ON "PIA"."Categories" TO "SYS";
  GRANT INDEX ON "PIA"."Categories" TO "SYS";
  GRANT INSERT ON "PIA"."Categories" TO "SYS";
  GRANT SELECT ON "PIA"."Categories" TO "SYS";
  GRANT UPDATE ON "PIA"."Categories" TO "SYS";
  GRANT REFERENCES ON "PIA"."Categories" TO "SYS";
  GRANT READ ON "PIA"."Categories" TO "SYS";
  GRANT ON COMMIT REFRESH ON "PIA"."Categories" TO "SYS";
  GRANT QUERY REWRITE ON "PIA"."Categories" TO "SYS";
  GRANT DEBUG ON "PIA"."Categories" TO "SYS";
  GRANT FLASHBACK ON "PIA"."Categories" TO "SYS";
--------------------------------------------------------
--  DDL for Table Customers
--------------------------------------------------------

  CREATE TABLE "PIA"."Customers" 
   (	"customer_id" NUMBER, 
	"first_name" VARCHAR2(255 BYTE), 
	"last_name" VARCHAR2(255 BYTE), 
	"email" VARCHAR2(255 BYTE), 
	"phone_number" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table Employees
--------------------------------------------------------

  CREATE TABLE "PIA"."Employees" 
   (	"employee_id" NUMBER, 
	"first_name" VARCHAR2(255 BYTE), 
	"last_name" VARCHAR2(255 BYTE), 
	"middle_name" VARCHAR2(255 BYTE), 
	"email" VARCHAR2(255 BYTE), 
	"phone_number" VARCHAR2(255 BYTE), 
	"position" VARCHAR2(255 BYTE), 
	"salary" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table Orders
--------------------------------------------------------

  CREATE TABLE "PIA"."Orders" 
   (	"order_id" NUMBER, 
	"order_date" DATE, 
	"status" VARCHAR2(255 BYTE), 
	"customer_id" NUMBER, 
	"product_id" NUMBER, 
	"quantity" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table Positions
--------------------------------------------------------

  CREATE TABLE "PIA"."Positions" 
   (	"position_id" NUMBER, 
	"position_name" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table Products
--------------------------------------------------------

  CREATE TABLE "PIA"."Products" 
   (	"product_id" NUMBER, 
	"product_name" VARCHAR2(255 BYTE), 
	"category" VARCHAR2(255 BYTE), 
	"price" NUMBER, 
	"quantity" NUMBER, 
	"storage_location" VARCHAR2(255 BYTE), 
	"image" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("image") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table Reviews
--------------------------------------------------------

  CREATE TABLE "PIA"."Reviews" 
   (	"review_id" NUMBER, 
	"customer_id" NUMBER, 
	"product_id" NUMBER, 
	"rating" NUMBER, 
	"comment" VARCHAR2(255 BYTE), 
	"review_date" DATE, 
	"image" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("image") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table Sales
--------------------------------------------------------

  CREATE TABLE "PIA"."Sales" 
   (	"sale_id" NUMBER, 
	"quantity" NUMBER, 
	"sale_date" DATE, 
	"customer_id" NUMBER, 
	"product_id" NUMBER, 
	"salesperson_id" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CART_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIA"."CART_PK" ON "PIA"."Cart" ("cart_id") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CATEGORIES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIA"."CATEGORIES_PK" ON "PIA"."Categories" ("category_id") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007393
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIA"."SYS_C007393" ON "PIA"."Categories" ("category_name") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CUSTOMERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIA"."CUSTOMERS_PK" ON "PIA"."Customers" ("customer_id") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EMPLOYEES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIA"."EMPLOYEES_PK" ON "PIA"."Employees" ("employee_id", "first_name", "last_name", "middle_name", "email", "phone_number", "position", "salary") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ORDERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIA"."ORDERS_PK" ON "PIA"."Orders" ("order_id") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index POSITIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIA"."POSITIONS_PK" ON "PIA"."Positions" ("position_id") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007417
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIA"."SYS_C007417" ON "PIA"."Positions" ("position_name") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRODUCTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIA"."PRODUCTS_PK" ON "PIA"."Products" ("product_id") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REVIEWS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIA"."REVIEWS_PK" ON "PIA"."Reviews" ("review_id") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SALES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIA"."SALES_PK" ON "PIA"."Sales" ("sale_id") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger BI_CATEGORIES_CATEGORY_ID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "PIA"."BI_CATEGORIES_CATEGORY_ID" 
  before insert on "Categories"
  for each row
begin
  select "CATEGORIES_CATEGORY_ID_SEQ".nextval into :NEW."category_id" from dual;
end;


/
ALTER TRIGGER "PIA"."BI_CATEGORIES_CATEGORY_ID" ENABLE;
--------------------------------------------------------
--  Constraints for Table Cart
--------------------------------------------------------

  ALTER TABLE "PIA"."Cart" MODIFY ("cart_id" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Cart" MODIFY ("customer_id" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Cart" MODIFY ("product_id" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Cart" MODIFY ("quantity" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Cart" ADD CONSTRAINT "CART_PK" PRIMARY KEY ("cart_id")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table Categories
--------------------------------------------------------

  ALTER TABLE "PIA"."Categories" MODIFY ("category_id" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Categories" MODIFY ("category_name" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Categories" ADD CONSTRAINT "CATEGORIES_PK" PRIMARY KEY ("category_id")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PIA"."Categories" ADD UNIQUE ("category_name")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table Customers
--------------------------------------------------------

  ALTER TABLE "PIA"."Customers" MODIFY ("customer_id" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Customers" MODIFY ("first_name" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Customers" MODIFY ("last_name" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Customers" MODIFY ("email" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Customers" MODIFY ("phone_number" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Customers" ADD CONSTRAINT "CUSTOMERS_PK" PRIMARY KEY ("customer_id")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table Employees
--------------------------------------------------------

  ALTER TABLE "PIA"."Employees" MODIFY ("employee_id" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Employees" MODIFY ("first_name" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Employees" MODIFY ("last_name" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Employees" MODIFY ("email" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Employees" MODIFY ("phone_number" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Employees" MODIFY ("position" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Employees" MODIFY ("salary" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Employees" ADD CONSTRAINT "EMPLOYEES_PK" PRIMARY KEY ("employee_id", "first_name", "last_name", "middle_name", "email", "phone_number", "position", "salary")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table Orders
--------------------------------------------------------

  ALTER TABLE "PIA"."Orders" MODIFY ("order_id" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Orders" MODIFY ("order_date" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Orders" MODIFY ("status" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Orders" MODIFY ("customer_id" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Orders" MODIFY ("product_id" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Orders" ADD CONSTRAINT "ORDERS_PK" PRIMARY KEY ("order_id")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table Positions
--------------------------------------------------------

  ALTER TABLE "PIA"."Positions" MODIFY ("position_id" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Positions" MODIFY ("position_name" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Positions" ADD CONSTRAINT "POSITIONS_PK" PRIMARY KEY ("position_id")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PIA"."Positions" ADD UNIQUE ("position_name")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table Products
--------------------------------------------------------

  ALTER TABLE "PIA"."Products" MODIFY ("product_id" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Products" MODIFY ("product_name" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Products" MODIFY ("category" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Products" MODIFY ("price" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Products" MODIFY ("quantity" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Products" MODIFY ("storage_location" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Products" MODIFY ("image" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Products" ADD CONSTRAINT "PRODUCTS_PK" PRIMARY KEY ("product_id")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table Reviews
--------------------------------------------------------

  ALTER TABLE "PIA"."Reviews" MODIFY ("review_id" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Reviews" MODIFY ("customer_id" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Reviews" MODIFY ("product_id" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Reviews" MODIFY ("rating" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Reviews" MODIFY ("review_date" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Reviews" MODIFY ("image" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Reviews" ADD CONSTRAINT "REVIEWS_PK" PRIMARY KEY ("review_id")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table Sales
--------------------------------------------------------

  ALTER TABLE "PIA"."Sales" MODIFY ("sale_id" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Sales" MODIFY ("quantity" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Sales" MODIFY ("sale_date" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Sales" MODIFY ("customer_id" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Sales" MODIFY ("product_id" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Sales" MODIFY ("salesperson_id" NOT NULL ENABLE);
  ALTER TABLE "PIA"."Sales" ADD CONSTRAINT "SALES_PK" PRIMARY KEY ("sale_id")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table Cart
--------------------------------------------------------

  ALTER TABLE "PIA"."Cart" ADD CONSTRAINT "Cart_fk0" FOREIGN KEY ("customer_id")
	  REFERENCES "PIA"."Customers" ("customer_id") ENABLE;
  ALTER TABLE "PIA"."Cart" ADD CONSTRAINT "Cart_fk1" FOREIGN KEY ("product_id")
	  REFERENCES "PIA"."Products" ("product_id") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table Orders
--------------------------------------------------------

  ALTER TABLE "PIA"."Orders" ADD CONSTRAINT "Orders_fk0" FOREIGN KEY ("customer_id")
	  REFERENCES "PIA"."Customers" ("customer_id") ENABLE;
  ALTER TABLE "PIA"."Orders" ADD CONSTRAINT "Orders_fk1" FOREIGN KEY ("product_id")
	  REFERENCES "PIA"."Products" ("product_id") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table Reviews
--------------------------------------------------------

  ALTER TABLE "PIA"."Reviews" ADD CONSTRAINT "Reviews_fk0" FOREIGN KEY ("customer_id")
	  REFERENCES "PIA"."Customers" ("customer_id") ENABLE;
  ALTER TABLE "PIA"."Reviews" ADD CONSTRAINT "Reviews_fk1" FOREIGN KEY ("product_id")
	  REFERENCES "PIA"."Products" ("product_id") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table Sales
--------------------------------------------------------

  ALTER TABLE "PIA"."Sales" ADD CONSTRAINT "Sales_fk0" FOREIGN KEY ("customer_id")
	  REFERENCES "PIA"."Customers" ("customer_id") ENABLE;
  ALTER TABLE "PIA"."Sales" ADD CONSTRAINT "Sales_fk1" FOREIGN KEY ("product_id")
	  REFERENCES "PIA"."Products" ("product_id") ENABLE;
